name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Step 3: Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step 4: Clean the project
    - name: Clean project
      run: ./gradlew clean

    # Step 5: Build with Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Step 6: Archive the APK
    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    # Step 7: Print missing rules if available
    - name: Print missing rules
      run: |
        if [ -f filetree/build/outputs/mapping/release/missing_rules.txt ]; then
          cat filetree/build/outputs/mapping/release/missing_rules.txt
        else
          echo "Missing rules file not found."
        fi

    # Step 8: Print build log if available
    - name: Print build log
      run: |
        if [ -f app/build/reports/build.log ]; then
          cat app/build/reports/build.log
        else
          echo "Build log file not found."
        fi