name: Android CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'  
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Clean the project
      - name: Clean project
        run: ./gradlew clean

      # Step 5: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Step 6: Archive the debug APK
      - name: Archive debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      # Step 7: Archive the release APK
      - name: Archive release APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk